[package]
name = "msf-hasher"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
hashes = { version = "0.1.9", features = ["std"] }
rust-crypto = "0.2.36"
