[package]
name = "msf-hasher"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
rust-crypto = "0.2.36"

[dev-dependencies]
assert_cmd = "2.0.15"

[lints.clippy]
all = "warn"
