name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Clippy
      run: cargo clippy
    - name: Install nightly
      run: rustup toolchain install nightly
    - name: Install nightly fmt
      run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
    - name: Run fmt
      run: cargo +nightly fmt --check
